### ISSUE TITLE
Allow creation of "Asides"

### ISSUE THREAD

**Issue by goofballLogic** [YorgunKelebek/Peer-Programming-Blog#20]
In a blog post, I sometimes want to create a piece of content which is part of the blog, but not really part of the main flow of text. It's a quick note about something related but not the main focus of what I'm writing about. 

It would be nice to be able to show this as an "aside" - something marked out from the surrounding text as not part of the main thread.

Here's one example of how it can look: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside

Here's another: http://www.html5marketplace.com/html5/aside.shtml

Here's an example from book typography: https://www.1106design.com/wp-content/uploads/2019/09/Nonfiction.png

**Comment by goofballLogic** [comment]
Another example from typography: https://www.latextemplates.com/wp-content/uploads/2019/06/book_5.jpg

**Comment by YorgunKelebek** [comment]
I think this can be achieved by a new 'content type snippet' we can define on Kentico Kontent. Much the same as the one we have for media embed item. We can then style these on the front-end.

These can be styled within the blog body like the first example above (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside). If we want these to be placed on the sidebar i.e. aside from the main blog body, then we could use linked content, adding the aside content as separate items and linking to the blog post. However, we would not be able to tie these to a specific point (text block/paragraph) in the blog body...

**Comment by goofballLogic** [comment]
Ok I think the simplest solution is probably best for now.

**Comment by goofballLogic** [comment]
Hmm. I have another wrinkle in this issue. I just came up against a case where I want to include a (3-line) code snippet, plus an image (click to open) which I ideally want in an aside. You can see it in "A minimalist experiment 12".

Maybe we should revert to your original styling etc for short aside "notes" and create an additional larger aside "block" for when we need richer content?

**Comment by YorgunKelebek** [comment]
What makes this large piece of content an 'aside'? Is it because it is not directly related to the topic?

I guess we are just talking about different ways of formatting an 'aside' so could add a property to the aside content type, ad call it, say 'format' with a list for different styling options, which could well correspond to a class in CSS?

**Comment by goofballLogic** [comment]
>What makes this large piece of content an 'aside'? Is it because it is not directly related to the topic?

Yes - this is content which isn't related to the main thread of the post.

TBH, I'd be quite happy for it not to render inline at all - it could show up e.g. only when you click a link, expand a section, pop-up a dialog etc.

Here's the example I was thinking of:

![Screen Shot 2020-02-24 at 15 12 51](https://user-images.githubusercontent.com/910448/75164102-2d5b2100-5718-11ea-9201-2f4e7551bef2.png)

**Comment by YorgunKelebek** [comment]
@goofballLogic Please test if https://github.com/YorgunKelebek/Peer-Programming-Blog/pull/41 satisfies this requirement.

**Comment by goofballLogic** [comment]
I've moved the content into the new type of Block aside. Once it's published I can see how it looks.

**Comment by goofballLogic** [comment]
I think you're done with this now? If so I'll close it. Will explore a different method of doing asides in my parallel version.

**Comment by YorgunKelebek** [comment]
Yes please
