### ISSUE TITLE
Top-alignment of blog posts in list

### ISSUE THREAD

**Issue by goofballLogic** [YorgunKelebek/Peer-Programming-Blog#21]
At least in my browser, there's something wrong with how the list of blog posts is rendering.

![Screen Shot 2020-02-16 at 13 59 12](https://user-images.githubusercontent.com/910448/74605983-ad540c00-50c4-11ea-9bd9-28a138a6bfc3.png)

It looks like the content from post 2 is intruding over the top of post 1 somehow. This may be because I don't always have a header photo in my blog posts?

**Comment by YorgunKelebek** [comment]
It is not so much the header, but it is the lack of blog post image. Styling is designed to overlap the blog body with the post image a little bit:

![image](https://user-images.githubusercontent.com/56796626/74606586-a24faa80-50c9-11ea-9854-5746b675335c.png)

**Comment by goofballLogic** [comment]
Ah ok so we need to make it adapt when there is no header image
