### ISSUE TITLE
"Post date" and "last modified"

### ISSUE THREAD

**Issue by goofballLogic** [YorgunKelebek/Peer-Programming-Blog#36]
As I was working on the most recent bit of implementation, I started to realise that the meaning of "Post date" is a bit ambiguous for our blog posts. It isn't the date we actually publish on - by the time a post clears review and I hit the publish button it's frequently the next day (or next week in some cases).

We also have the system generated last_modified field but that only records the last time it changed to published - so we don't have a record of the original post date if we make a change and republish.

Furthermore, I was working on using Intl.RelativeTimeFormat to illustrate the potential for things like "5 minutes ago", "1 hour ago", "2 days ago" etc. when I realised that post_date is only a date - no time, so it made the exercise a little pointless. 

Is there some better way in Kentico to track publication datetimes?

**Comment by YorgunKelebek** [comment]
I don't think last modified is reliable as a post can be modified after it's published. Unless we are interested in that and want to push it up the list when modified...?

Published date is of type datetime, and time is optional on Kentico editing interface:

![image](https://user-images.githubusercontent.com/56796626/75118458-43160b00-5672-11ea-9b09-b520f898fbc7.png)

I see this date as our choice, i.e. we set it to when we want it to be, I see that with the editing/publishing workflow it could be confusing. Not sure what the best answer is here...

**Comment by goofballLogic** [comment]
When something is published kentico doesn't seem to let you modify it - instead you have to create a new "version". Does that change the last_modified date in the published item?

⁣Sent from BlueMail ​


-------- Original Message --------

**Comment by YorgunKelebek** [comment]
> When something is published kentico doesn't seem to let you modify it - instead you have to create a new "version". Does that change the last_modified date in the published item? ⁣

Yes it does
```

  "item": {
    "system": {
      "id": "2f262011-7810-42dc-bb9d-59d07f345c51",
      "name": "Building Blogs - Part 1",
      "codename": "building_blogs___part_1",
      "language": "default",
      "type": "blog_post",
      "sitemap_locations": [],
      "last_modified": "2020-02-21T17:24:02.1675457Z"
    },
```

**Comment by goofballLogic** [comment]
That seems like a strange decision by kentico

**Comment by goofballLogic** [comment]
It's really strange we can't access this - the data is clearly used by their own UI. Why would they not expose it via API? I've stuck a question on StackOverflow to see if I get any bites.

**Comment by YorgunKelebek** [comment]
> It's really strange we can't access this - the data is clearly used by their own UI. Why would they not expose it via API? I've stuck a question on StackOverflow to see if I get any bites.

I am not sure what you say we cannot access? We can access the last modified date, as well as the blog post date, with the time if provided by the editors.

**Comment by goofballLogic** [comment]
In the UI you can see the date an item was published as shown below ("Published" column), but there doesn't appear to be equivalent API access:

![Screen Shot 2020-02-24 at 12 17 08](https://user-images.githubusercontent.com/910448/75151945-cf224400-56ff-11ea-89b0-344afbff59f2.png)

**Comment by goofballLogic** [comment]
Nobody is responding on SO: https://stackoverflow.com/questions/60368184/how-can-i-retrieve-workflow-dates-from-kentico-kontents-aka-kentico-cloud-api

**Comment by YorgunKelebek** [comment]
I suspect this might be tricky as a content item could go through multiple workflow steps continuously, back and forth...

However, with the premium version, combination of 'webhooks' and management API could be used to update the blog's published on custom property each time [or first time only?] it hits the published state.

**Comment by goofballLogic** [comment]
ah interesting. Still, they clearly have this data internally. Weird that they don't just expose it.

**Comment by goofballLogic** [comment]
Well I don't see any answers coming in on stackoverflow, and the kontent guys on the community discussion chat aren't responding either. I reckon this is just not doable currently so I'm going to go ahead and close it. 

This will definitely mean I recommend a different CMS option for an upcoming project at work. I wouldn't want to trust their API for a production architecture after this. Maybe this is just a v1? Perhaps they will make it more complete over time...
