### ISSUE TITLE
Quotations

### ISSUE THREAD

**Issue by goofballLogic** [YorgunKelebek/Peer-Programming-Blog#38]
I'm wanting to quote from a standards document, so I need to add a new content type. I'm adding this here to note that we need to support it and in case you have a better idea?

**Comment by YorgunKelebek** [comment]
Could possible tie this is with this idea: https://github.com/YorgunKelebek/Peer-Programming-Blog/issues/20#issuecomment-590351000

i.e. one of the formatting options could be 'quotation'

**Comment by goofballLogic** [comment]
I don't think a quotation is an "aside" - it's not orthogonal to the flow of the main argument. The [content type I created for it](https://app.kontent.ai/99b0b3b0-4838-0051-3d57-8af72f55e8a0/content-models/types/edit/f65ad16e-49db-42d6-8e3c-11057db6cbb1) has a section for "Quote" and a section for "Reference".

**Comment by YorgunKelebek** [comment]
Could close this as well, if you are happy with the implementation...?

**Comment by goofballLogic** [comment]
Well, I suppose it depends how we are assessing these things.

## Visual interest

It looks quite ornate which is visually interesting:

![Screen Shot 2020-03-08 at 19 05 34](https://user-images.githubusercontent.com/910448/76169437-079a3700-6170-11ea-8a7e-02da8e2dac79.png)

## Mobile-first

It's fairly clear on mobile too, although I note that it fails to properly wrap long content:

![Screen Shot 2020-03-08 at 19 11 30](https://user-images.githubusercontent.com/910448/76169493-b63e7780-6170-11ea-89fd-08eb30c4f1f0.png)

## Readability

The [Nielsen-Norman Group](https://www.nngroup.com/articles/legibility-readability-comprehension/) list the following as basic readability UX concerns:
1. Use a reasonably large default font size and allow users to change the font size
1. Have high contrast between characters and background
1. Use a clean typeface

Which I think this meets although I have questions about (2) because the beautiful quotation header maybe makes it slightly harder for people struggling with vision to distinguish text from background? I note that it seems to only be a problem on desktop:

![Screen Shot 2020-03-08 at 19 17 42](https://user-images.githubusercontent.com/910448/76169593-a4110900-6171-11ea-8f9b-e10228466ef5.png)

On desktop, it's also hard to know where one quotation starts and ends, especially if there are two in quick succession (as shown above).

**Comment by YorgunKelebek** [comment]
#51 
![image](https://user-images.githubusercontent.com/56796626/77857478-93decd80-71f5-11ea-96ab-bcd33b5723ef.png)

**Comment by goofballLogic** [comment]
That will fix the styling, although not the mobile wrapping

**Comment by YorgunKelebek** [comment]
> That will fix the styling, although not the mobile wrapping

Wrapping issue is with long URLs in links, not sure what can be done about that, except at the editing level. If you know of a way let me know though.

**Comment by goofballLogic** [comment]
maybe something like
```
.blog-post a {
    color: #76c158;
    word-break: break-word;
}
``` ?
Not sure if you can link that to small width displays with your responsive framework that you're using ?

**Comment by YorgunKelebek** [comment]
OK, that worked - thanks
