### ISSUE TITLE
Kentico UI crash / corruption

### ISSUE THREAD

**Issue by goofballLogic** [YorgunKelebek/Peer-Programming-Blog#40]
Kentico letting us down again. As I was editing it suddenly corrupted the editing screen like this:

![Screen Shot 2020-02-29 at 11 23 01](https://user-images.githubusercontent.com/910448/75606567-f3a66380-5ae5-11ea-9525-5b8522f2960b.png)

I'm using a major browser - I don't think there's any excuse for this type of behaviour. Should we consider a different CMS @YorgunKelebek ?

**Comment by YorgunKelebek** [comment]
Hmmm, that's no good. I am open to suggestions for alternatives. After all, we are experimenting still and reviewing Kentico Kontent. Let's shop around...

**Comment by goofballLogic** [comment]
I really want to write one but its the last thing I need to spend my time on. this can be a low priority thing for now.

**Comment by goofballLogic** [comment]
Closing as I think this is a moot point for now.
