### ISSUE TITLE
'Preview' feature

### ISSUE THREAD

**Issue by YorgunKelebek** [YorgunKelebek/Peer-Programming-Blog#43]
We need a preview feature (or 'mode') for seeing how unpublished content on Kentico would look on our blog. Apart form being a nice feature for content preview, it would be useful for development.

**Comment by goofballLogic** [comment]
ok should be fairly simple with the built-in kentico support, but it will be hard not to expose this functionality to the public

**Comment by goofballLogic** [comment]
We could prompt to enter the API key for preview mode. That way we wouldn't be hard coding it into our source code.

**Comment by YorgunKelebek** [comment]
That's a good idea!

**Comment by YorgunKelebek** [comment]
Go ahead and preview your unpublished blog entry on Kontent:

![image](https://user-images.githubusercontent.com/56796626/79116399-4bd8b280-7d80-11ea-8c35-7b3ed66ee620.png)
