### ISSUE TITLE
Ability to link to specific blog post

### ISSUE THREAD

**Issue by goofballLogic** [YorgunKelebek/Peer-Programming-Blog#46]
If I want to write a blog and send someone a link, I don't want them to have to go through the entire list to find it (or even search). I need a way to send them a link to a specific post.

**Comment by YorgunKelebek** [comment]
@goofballLogic Please close if you are happy with the implementation

**Comment by goofballLogic** [comment]
Seems to work well, although I note that a hash tag will navigate you to a random spot on the page if the code name of the blog post matches the id of any element.
